# Project information
site_name: Portal de Processos SEFAZ
site_url: https://squidfunk.github.io/mkdocs-material/
site_author: Martin Donath
site_description: >-
  A Coordenadoria de Tecnologia da Informação e Comunicação - COT, 
  apresenta o Portal de Processos, com o objetivo de melhorar a qualidade dos produtos desenvolvidos,
  contendo a metodologia de trabalho para nortear a prestação dos seus serviços de forma mais eficaz


# Copyright
copyright: Copyright &copy; 2020 COT SEFAZ

# Configuration
theme:
  name: material
  custom_dir: material
  config[extra_css]: extra_css/sefaz.css
 
  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - tabs
    #- instant
    - navigation.expand
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  icon:
  logo: icoPPS.png
  favicon: favicon.png

  config[extra_js]: mermaid.min.js
  extra_javascript:
  - https://cdn.rawgit.com/knsv/mermaid/0.5.6/dist/mermaid.min.js
  
# Plugins
plugins:
  - search
  - macros
#  - minify:
#      minify_html: true


extra_javascript :
    - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.tables
  - markdown.extensions.abbr
  - markdown.extensions.md_in_html
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
      #toc_depth: 2
      #baselevel: 2
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/icons
  # - pymdownx.highlight:
    # linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
       - name: mermaid
         class: mermaid
         format: !!python/name:pymdownx.superfences.fence_div_format       
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Home: getting-started
  - Md Exemplo: markdown-example.md
  - Md Exemplo2: markdown-example.md  
  - Estrutura e Serviços: 
    - Estrutura: 'estrutura/index.md'
  - Processos:
    - Processos:  
      - Desenvolvimento de software: 'processos/index.md' 
  - Papéis:
    - Papéis: 'papeis/index.md'
    - Administrador de Dados: 'papeis/admdados.md'
    - Analista de Requisitos: 'papeis/analistarequisitos.md'
    - Analista de Testes: 'papeis/analistatestes.md'
    - Área de Infraestrutura: 'papeis/areainfra.md'
    - Arquiteto de Software: 'papeis/arquitetosoftware.md'
    - Auditor de Negócio: 'papeis/auditornegocio.md'
    - Coordenação de Tecnologia e Comunicação: 'papeis/cot.md'
    - Consultor de Negócio: 'papeis/consultornegocios.md'
    - DBA: 'papeis/dba.md'
    - Desenvolvedor: 'papeis/desenvolvedor.md'
    - Qualidade e Governança: 'papeis/governanca.md'
    - Gestor de Negócio: 'papeis/gestornegocio.md'
    - Gerente de Projeto: 'papeis/gerenteprojeto.md'
    - Grupos Envolvidos: 'papeis/grupos.md'
    - Líder do Projeto: 'papeis/liderprojeto.md'
    - Tester : 'papeis/tester.md'
  - Políticas:
    - Admonition: level/one.md
  - Ciclos de Vida: 
    - Ciclo de Vida: ciclodevida.md
  - Templates:
    - Admonition: level/one.md
  - Ferramentas:
    - Admonition: level/one.md
  - Procedimentos e Padrões:
    - Admonition: level/one.md
    
# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto
